/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = 1503741456;

    private final Integer id;
    private final String  streetName;

    public Address(Address value) {
        this.id = value.id;
        this.streetName = value.streetName;
    }

    public Address(
        Integer id,
        String  streetName
    ) {
        this.id = id;
        this.streetName = streetName;
    }

    public Integer getId() {
        return this.id;
    }

    public String getStreetName() {
        return this.streetName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(id);
        sb.append(", ").append(streetName);

        sb.append(")");
        return sb.toString();
    }
}
