/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Developers implements Serializable {

    private static final long serialVersionUID = 33016279;

    private final Integer id;
    private final String  fio;
    private final String  phone;
    private final String  email;

    public Developers(Developers value) {
        this.id = value.id;
        this.fio = value.fio;
        this.phone = value.phone;
        this.email = value.email;
    }

    public Developers(
        Integer id,
        String  fio,
        String  phone,
        String  email
    ) {
        this.id = id;
        this.fio = fio;
        this.phone = phone;
        this.email = email;
    }

    public Integer getId() {
        return this.id;
    }

    public String getFio() {
        return this.fio;
    }

    public String getPhone() {
        return this.phone;
    }

    public String getEmail() {
        return this.email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Developers (");

        sb.append(id);
        sb.append(", ").append(fio);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
