/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Example implements Serializable {

    private static final long serialVersionUID = -527958590;

    private final Integer id;
    private final String  letter;

    public Example(Example value) {
        this.id = value.id;
        this.letter = value.letter;
    }

    public Example(
        Integer id,
        String  letter
    ) {
        this.id = id;
        this.letter = letter;
    }

    public Integer getId() {
        return this.id;
    }

    public String getLetter() {
        return this.letter;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Example (");

        sb.append(id);
        sb.append(", ").append(letter);

        sb.append(")");
        return sb.toString();
    }
}
