/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Languages implements Serializable {

    private static final long serialVersionUID = 1111452103;

    private final Integer id;
    private final String  language;

    public Languages(Languages value) {
        this.id = value.id;
        this.language = value.language;
    }

    public Languages(
        Integer id,
        String  language
    ) {
        this.id = id;
        this.language = language;
    }

    public Integer getId() {
        return this.id;
    }

    public String getLanguage() {
        return this.language;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Languages (");

        sb.append(id);
        sb.append(", ").append(language);

        sb.append(")");
        return sb.toString();
    }
}
