/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Passports implements Serializable {

    private static final long serialVersionUID = -1518215268;

    private final Long   id;
    private final String registration;

    public Passports(Passports value) {
        this.id = value.id;
        this.registration = value.registration;
    }

    public Passports(
        Long   id,
        String registration
    ) {
        this.id = id;
        this.registration = registration;
    }

    public Long getId() {
        return this.id;
    }

    public String getRegistration() {
        return this.registration;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Passports (");

        sb.append(id);
        sb.append(", ").append(registration);

        sb.append(")");
        return sb.toString();
    }
}
