/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Saleitems implements Serializable {

    private static final long serialVersionUID = 1959426186;

    private final Integer id;
    private final Integer idSale;
    private final String  item;

    public Saleitems(Saleitems value) {
        this.id = value.id;
        this.idSale = value.idSale;
        this.item = value.item;
    }

    public Saleitems(
        Integer id,
        Integer idSale,
        String  item
    ) {
        this.id = id;
        this.idSale = idSale;
        this.item = item;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getIdSale() {
        return this.idSale;
    }

    public String getItem() {
        return this.item;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Saleitems (");

        sb.append(id);
        sb.append(", ").append(idSale);
        sb.append(", ").append(item);

        sb.append(")");
        return sb.toString();
    }
}
