/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sale implements Serializable {

    private static final long serialVersionUID = -666347232;

    private final Double cost;
    private final byte[] items;

    public Sale(Sale value) {
        this.cost = value.cost;
        this.items = value.items;
    }

    public Sale(
        Double cost,
        byte[] items
    ) {
        this.cost = cost;
        this.items = items;
    }

    public Double getCost() {
        return this.cost;
    }

    public byte[] getItems() {
        return this.items;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sale (");

        sb.append(cost);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
