/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userslanguages implements Serializable {

    private static final long serialVersionUID = 569149153;

    private final Integer id;
    private final Integer idUser;
    private final Integer idLanguage;

    public Userslanguages(Userslanguages value) {
        this.id = value.id;
        this.idUser = value.idUser;
        this.idLanguage = value.idLanguage;
    }

    public Userslanguages(
        Integer id,
        Integer idUser,
        Integer idLanguage
    ) {
        this.id = id;
        this.idUser = idUser;
        this.idLanguage = idLanguage;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getIdUser() {
        return this.idUser;
    }

    public Integer getIdLanguage() {
        return this.idLanguage;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userslanguages (");

        sb.append(id);
        sb.append(", ").append(idUser);
        sb.append(", ").append(idLanguage);

        sb.append(")");
        return sb.toString();
    }
}
