/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Usersales implements Serializable {

    private static final long serialVersionUID = 1247277572;

    private final Integer id;
    private final Integer idUser;
    private final Integer idSale;

    public Usersales(Usersales value) {
        this.id = value.id;
        this.idUser = value.idUser;
        this.idSale = value.idSale;
    }

    public Usersales(
        Integer id,
        Integer idUser,
        Integer idSale
    ) {
        this.id = id;
        this.idUser = idUser;
        this.idSale = idSale;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getIdUser() {
        return this.idUser;
    }

    public Integer getIdSale() {
        return this.idSale;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Usersales (");

        sb.append(id);
        sb.append(", ").append(idUser);
        sb.append(", ").append(idSale);

        sb.append(")");
        return sb.toString();
    }
}
