/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersAddress implements Serializable {

    private static final long serialVersionUID = -1346719734;

    private final Integer addressId;
    private final Integer id;

    public UsersAddress(UsersAddress value) {
        this.addressId = value.addressId;
        this.id = value.id;
    }

    public UsersAddress(
        Integer addressId,
        Integer id
    ) {
        this.addressId = addressId;
        this.id = id;
    }

    public Integer getAddressId() {
        return this.addressId;
    }

    public Integer getId() {
        return this.id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UsersAddress (");

        sb.append(addressId);
        sb.append(", ").append(id);

        sb.append(")");
        return sb.toString();
    }
}
