/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = -790485822;

    private final Integer id;
    private final String  email;
    private final String  fio;
    private final String  phone;
    private final Long    passportId;
    private final Integer personId;

    public User(User value) {
        this.id = value.id;
        this.email = value.email;
        this.fio = value.fio;
        this.phone = value.phone;
        this.passportId = value.passportId;
        this.personId = value.personId;
    }

    public User(
        Integer id,
        String  email,
        String  fio,
        String  phone,
        Long    passportId,
        Integer personId
    ) {
        this.id = id;
        this.email = email;
        this.fio = fio;
        this.phone = phone;
        this.passportId = passportId;
        this.personId = personId;
    }

    public Integer getId() {
        return this.id;
    }

    public String getEmail() {
        return this.email;
    }

    public String getFio() {
        return this.fio;
    }

    public String getPhone() {
        return this.phone;
    }

    public Long getPassportId() {
        return this.passportId;
    }

    public Integer getPersonId() {
        return this.personId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(fio);
        sb.append(", ").append(phone);
        sb.append(", ").append(passportId);
        sb.append(", ").append(personId);

        sb.append(")");
        return sb.toString();
    }
}
