/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables.records;


import com.arishenk.jook.Database.tables.Saleitems;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SaleitemsRecord extends UpdatableRecordImpl<SaleitemsRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = -166778417;

    /**
     * Setter for <code>SALEITEMS.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>SALEITEMS.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>SALEITEMS.id_sale</code>.
     */
    public void setIdSale(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>SALEITEMS.id_sale</code>.
     */
    public Integer getIdSale() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>SALEITEMS.item</code>.
     */
    public void setItem(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SALEITEMS.item</code>.
     */
    public String getItem() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Saleitems.SALEITEMS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Saleitems.SALEITEMS.ID_SALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Saleitems.SALEITEMS.ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdSale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdSale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SaleitemsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SaleitemsRecord value2(Integer value) {
        setIdSale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SaleitemsRecord value3(String value) {
        setItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SaleitemsRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SaleitemsRecord
     */
    public SaleitemsRecord() {
        super(Saleitems.SALEITEMS);
    }

    /**
     * Create a detached, initialised SaleitemsRecord
     */
    public SaleitemsRecord(Integer id, Integer idSale, String item) {
        super(Saleitems.SALEITEMS);

        set(0, id);
        set(1, idSale);
        set(2, item);
    }
}
