/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables;


import com.arishenk.jook.Database.DefaultSchema;
import com.arishenk.jook.Database.tables.records.DevelopersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Developers extends TableImpl<DevelopersRecord> {

    private static final long serialVersionUID = -1892540918;

    /**
     * The reference instance of <code>DEVELOPERS</code>
     */
    public static final Developers DEVELOPERS = new Developers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DevelopersRecord> getRecordType() {
        return DevelopersRecord.class;
    }

    /**
     * The column <code>DEVELOPERS.id</code>.
     */
    public final TableField<DevelopersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>DEVELOPERS.fio</code>.
     */
    public final TableField<DevelopersRecord, String> FIO = createField("fio", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>DEVELOPERS.phone</code>.
     */
    public final TableField<DevelopersRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>DEVELOPERS.email</code>.
     */
    public final TableField<DevelopersRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * Create a <code>DEVELOPERS</code> table reference
     */
    public Developers() {
        this(DSL.name("DEVELOPERS"), null);
    }

    /**
     * Create an aliased <code>DEVELOPERS</code> table reference
     */
    public Developers(String alias) {
        this(DSL.name(alias), DEVELOPERS);
    }

    /**
     * Create an aliased <code>DEVELOPERS</code> table reference
     */
    public Developers(Name alias) {
        this(alias, DEVELOPERS);
    }

    private Developers(Name alias, Table<DevelopersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Developers(Name alias, Table<DevelopersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DevelopersRecord, Integer> getIdentity() {
        return Internal.createIdentity(com.arishenk.jook.Database.tables.Developers.DEVELOPERS, com.arishenk.jook.Database.tables.Developers.DEVELOPERS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DevelopersRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.arishenk.jook.Database.tables.Developers.DEVELOPERS, "KEY_DEVELOPERS_PRIMARY", com.arishenk.jook.Database.tables.Developers.DEVELOPERS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DevelopersRecord>> getKeys() {
        return Arrays.<UniqueKey<DevelopersRecord>>asList(
              Internal.createUniqueKey(com.arishenk.jook.Database.tables.Developers.DEVELOPERS, "KEY_DEVELOPERS_PRIMARY", com.arishenk.jook.Database.tables.Developers.DEVELOPERS.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Developers as(String alias) {
        return new Developers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Developers as(Name alias) {
        return new Developers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Developers rename(String name) {
        return new Developers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Developers rename(Name name) {
        return new Developers(name, null);
    }
}
