/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables;


import com.arishenk.jook.Database.DefaultSchema;
import com.arishenk.jook.Database.tables.records.ManagersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Managers extends TableImpl<ManagersRecord> {

    private static final long serialVersionUID = -735187394;

    /**
     * The reference instance of <code>MANAGERS</code>
     */
    public static final Managers MANAGERS = new Managers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManagersRecord> getRecordType() {
        return ManagersRecord.class;
    }

    /**
     * The column <code>MANAGERS.id</code>.
     */
    public final TableField<ManagersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>MANAGERS.fio</code>.
     */
    public final TableField<ManagersRecord, String> FIO = createField("fio", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>MANAGERS.phone</code>.
     */
    public final TableField<ManagersRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>MANAGERS.email</code>.
     */
    public final TableField<ManagersRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>MANAGERS.sales</code>.
     */
    public final TableField<ManagersRecord, String> SALES = createField("sales", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>MANAGERS</code> table reference
     */
    public Managers() {
        this(DSL.name("MANAGERS"), null);
    }

    /**
     * Create an aliased <code>MANAGERS</code> table reference
     */
    public Managers(String alias) {
        this(DSL.name(alias), MANAGERS);
    }

    /**
     * Create an aliased <code>MANAGERS</code> table reference
     */
    public Managers(Name alias) {
        this(alias, MANAGERS);
    }

    private Managers(Name alias, Table<ManagersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Managers(Name alias, Table<ManagersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ManagersRecord, Integer> getIdentity() {
        return Internal.createIdentity(com.arishenk.jook.Database.tables.Managers.MANAGERS, com.arishenk.jook.Database.tables.Managers.MANAGERS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ManagersRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.arishenk.jook.Database.tables.Managers.MANAGERS, "KEY_MANAGERS_PRIMARY", com.arishenk.jook.Database.tables.Managers.MANAGERS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ManagersRecord>> getKeys() {
        return Arrays.<UniqueKey<ManagersRecord>>asList(
              Internal.createUniqueKey(com.arishenk.jook.Database.tables.Managers.MANAGERS, "KEY_MANAGERS_PRIMARY", com.arishenk.jook.Database.tables.Managers.MANAGERS.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Managers as(String alias) {
        return new Managers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Managers as(Name alias) {
        return new Managers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Managers rename(String name) {
        return new Managers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Managers rename(Name name) {
        return new Managers(name, null);
    }
}
