/*
 * This file is generated by jOOQ.
 */
package com.arishenk.jook.Database.tables;


import com.arishenk.jook.Database.DefaultSchema;
import com.arishenk.jook.Database.tables.records.UserslanguagesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userslanguages extends TableImpl<UserslanguagesRecord> {

    private static final long serialVersionUID = -759135858;

    /**
     * The reference instance of <code>USERSLANGUAGES</code>
     */
    public static final Userslanguages USERSLANGUAGES = new Userslanguages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserslanguagesRecord> getRecordType() {
        return UserslanguagesRecord.class;
    }

    /**
     * The column <code>USERSLANGUAGES.id</code>.
     */
    public final TableField<UserslanguagesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>USERSLANGUAGES.id_user</code>.
     */
    public final TableField<UserslanguagesRecord, Integer> ID_USER = createField("id_user", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>USERSLANGUAGES.id_language</code>.
     */
    public final TableField<UserslanguagesRecord, Integer> ID_LANGUAGE = createField("id_language", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>USERSLANGUAGES</code> table reference
     */
    public Userslanguages() {
        this(DSL.name("USERSLANGUAGES"), null);
    }

    /**
     * Create an aliased <code>USERSLANGUAGES</code> table reference
     */
    public Userslanguages(String alias) {
        this(DSL.name(alias), USERSLANGUAGES);
    }

    /**
     * Create an aliased <code>USERSLANGUAGES</code> table reference
     */
    public Userslanguages(Name alias) {
        this(alias, USERSLANGUAGES);
    }

    private Userslanguages(Name alias, Table<UserslanguagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Userslanguages(Name alias, Table<UserslanguagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<UserslanguagesRecord, Integer> getIdentity() {
        return Internal.createIdentity(com.arishenk.jook.Database.tables.Userslanguages.USERSLANGUAGES, com.arishenk.jook.Database.tables.Userslanguages.USERSLANGUAGES.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserslanguagesRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.arishenk.jook.Database.tables.Userslanguages.USERSLANGUAGES, "KEY_USERSLANGUAGES_PRIMARY", com.arishenk.jook.Database.tables.Userslanguages.USERSLANGUAGES.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserslanguagesRecord>> getKeys() {
        return Arrays.<UniqueKey<UserslanguagesRecord>>asList(
              Internal.createUniqueKey(com.arishenk.jook.Database.tables.Userslanguages.USERSLANGUAGES, "KEY_USERSLANGUAGES_PRIMARY", com.arishenk.jook.Database.tables.Userslanguages.USERSLANGUAGES.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Userslanguages as(String alias) {
        return new Userslanguages(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Userslanguages as(Name alias) {
        return new Userslanguages(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Userslanguages rename(String name) {
        return new Userslanguages(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Userslanguages rename(Name name) {
        return new Userslanguages(name, null);
    }
}
